version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mcdm
      MYSQL_ROOT_PASSWORD: root

  backend:
    build:
      context: ./pfa2021  # Utilisez le répertoire actuel où se trouve le Dockerfile du backend
      dockerfile: DockerFile  # Assurez-vous que le Dockerfile est dans le même répertoire que docker-compose.yml
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mcdm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_started

  frontend:
    build:
      context: ./argon-design-system-angular-master  # Utilise le répertoire actuel où se trouve le Dockerfile du frontend
      dockerfile: DockerFile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
